# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'records.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(881, 728)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 861, 461))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.searchLE = QtWidgets.QLineEdit(self.widget)
        self.searchLE.setObjectName("searchLE")
        self.gridLayout.addWidget(self.searchLE, 0, 2, 1, 1)
        self.marketComboBox = QtWidgets.QComboBox(self.widget)
        self.marketComboBox.setObjectName("marketComboBox")
        self.gridLayout.addWidget(self.marketComboBox, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.chooseButton = QtWidgets.QPushButton(self.widget)
        self.chooseButton.setObjectName("chooseButton")
        self.gridLayout.addWidget(self.chooseButton, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)
        self.productRecordsTable = QtWidgets.QTableView(self.widget)
        self.productRecordsTable.setObjectName("productRecordsTable")
        self.gridLayout.addWidget(self.productRecordsTable, 1, 2, 2, 1)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(10, 480, 861, 171))
        self.widget1.setObjectName("widget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.chosenProductsTable = QtWidgets.QTableView(self.widget1)
        self.chosenProductsTable.setObjectName("chosenProductsTable")
        self.gridLayout_2.addWidget(self.chosenProductsTable, 0, 1, 1, 3)
        self.compareButton = QtWidgets.QPushButton(self.widget1)
        self.compareButton.setObjectName("compareButton")
        self.gridLayout_2.addWidget(self.compareButton, 1, 3, 1, 1)
        self.deleteButton = QtWidgets.QPushButton(self.widget1)
        self.deleteButton.setObjectName("deleteButton")
        self.gridLayout_2.addWidget(self.deleteButton, 1, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.widget1)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 881, 31))
        self.menubar.setObjectName("menubar")
        self.mainMenu = QtWidgets.QMenu(self.menubar)
        self.mainMenu.setObjectName("mainMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionUpload = QtWidgets.QAction(MainWindow)
        self.actionUpload.setObjectName("actionUpload")
        self.mainMenu.addAction(self.actionUpload)
        self.menubar.addAction(self.mainMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Market"))
        self.chooseButton.setText(_translate("MainWindow", "Ürün Seç"))
        self.label.setText(_translate("MainWindow", "Arama:"))
        self.compareButton.setText(_translate("MainWindow", "Karşılaştır"))
        self.deleteButton.setText(_translate("MainWindow", "Sil"))
        self.label_3.setText(_translate("MainWindow", "Seçilen Ürünler"))
        self.mainMenu.setTitle(_translate("MainWindow", "Menü"))
        self.actionUpload.setText(_translate("MainWindow", "Kayıt Yükleme"))
